// ISO 3166-1 numeric → alpha-2 + English name.
// world-atlas TopoJSON keys countries by numeric ID; we map those into alpha-2
// so visitor data can be looked up consistently.

export type CountryInfo = { alpha2: string; name: string };

export const NUMERIC_TO_COUNTRY: Record<string, CountryInfo> = {
  '004': { alpha2: 'AF', name: 'Afghanistan' },
  '008': { alpha2: 'AL', name: 'Albania' },
  '010': { alpha2: 'AQ', name: 'Antarctica' },
  '012': { alpha2: 'DZ', name: 'Algeria' },
  '024': { alpha2: 'AO', name: 'Angola' },
  '031': { alpha2: 'AZ', name: 'Azerbaijan' },
  '032': { alpha2: 'AR', name: 'Argentina' },
  '036': { alpha2: 'AU', name: 'Australia' },
  '040': { alpha2: 'AT', name: 'Austria' },
  '044': { alpha2: 'BS', name: 'Bahamas' },
  '048': { alpha2: 'BH', name: 'Bahrain' },
  '050': { alpha2: 'BD', name: 'Bangladesh' },
  '051': { alpha2: 'AM', name: 'Armenia' },
  '056': { alpha2: 'BE', name: 'Belgium' },
  '064': { alpha2: 'BT', name: 'Bhutan' },
  '068': { alpha2: 'BO', name: 'Bolivia' },
  '070': { alpha2: 'BA', name: 'Bosnia and Herzegovina' },
  '072': { alpha2: 'BW', name: 'Botswana' },
  '076': { alpha2: 'BR', name: 'Brazil' },
  '084': { alpha2: 'BZ', name: 'Belize' },
  '096': { alpha2: 'BN', name: 'Brunei' },
  '100': { alpha2: 'BG', name: 'Bulgaria' },
  '104': { alpha2: 'MM', name: 'Myanmar' },
  '108': { alpha2: 'BI', name: 'Burundi' },
  '112': { alpha2: 'BY', name: 'Belarus' },
  '116': { alpha2: 'KH', name: 'Cambodia' },
  '120': { alpha2: 'CM', name: 'Cameroon' },
  '124': { alpha2: 'CA', name: 'Canada' },
  '140': { alpha2: 'CF', name: 'Central African Republic' },
  '144': { alpha2: 'LK', name: 'Sri Lanka' },
  '148': { alpha2: 'TD', name: 'Chad' },
  '152': { alpha2: 'CL', name: 'Chile' },
  '156': { alpha2: 'CN', name: 'China' },
  '158': { alpha2: 'TW', name: 'Taiwan' },
  '170': { alpha2: 'CO', name: 'Colombia' },
  '178': { alpha2: 'CG', name: 'Congo' },
  '180': { alpha2: 'CD', name: 'DR Congo' },
  '188': { alpha2: 'CR', name: 'Costa Rica' },
  '191': { alpha2: 'HR', name: 'Croatia' },
  '192': { alpha2: 'CU', name: 'Cuba' },
  '196': { alpha2: 'CY', name: 'Cyprus' },
  '203': { alpha2: 'CZ', name: 'Czechia' },
  '204': { alpha2: 'BJ', name: 'Benin' },
  '208': { alpha2: 'DK', name: 'Denmark' },
  '214': { alpha2: 'DO', name: 'Dominican Republic' },
  '218': { alpha2: 'EC', name: 'Ecuador' },
  '222': { alpha2: 'SV', name: 'El Salvador' },
  '226': { alpha2: 'GQ', name: 'Equatorial Guinea' },
  '231': { alpha2: 'ET', name: 'Ethiopia' },
  '232': { alpha2: 'ER', name: 'Eritrea' },
  '233': { alpha2: 'EE', name: 'Estonia' },
  '242': { alpha2: 'FJ', name: 'Fiji' },
  '246': { alpha2: 'FI', name: 'Finland' },
  '250': { alpha2: 'FR', name: 'France' },
  '254': { alpha2: 'GF', name: 'French Guiana' },
  '262': { alpha2: 'DJ', name: 'Djibouti' },
  '266': { alpha2: 'GA', name: 'Gabon' },
  '268': { alpha2: 'GE', name: 'Georgia' },
  '270': { alpha2: 'GM', name: 'Gambia' },
  '275': { alpha2: 'PS', name: 'Palestine' },
  '276': { alpha2: 'DE', name: 'Germany' },
  '288': { alpha2: 'GH', name: 'Ghana' },
  '300': { alpha2: 'GR', name: 'Greece' },
  '304': { alpha2: 'GL', name: 'Greenland' },
  '320': { alpha2: 'GT', name: 'Guatemala' },
  '324': { alpha2: 'GN', name: 'Guinea' },
  '328': { alpha2: 'GY', name: 'Guyana' },
  '332': { alpha2: 'HT', name: 'Haiti' },
  '340': { alpha2: 'HN', name: 'Honduras' },
  '348': { alpha2: 'HU', name: 'Hungary' },
  '352': { alpha2: 'IS', name: 'Iceland' },
  '356': { alpha2: 'IN', name: 'India' },
  '360': { alpha2: 'ID', name: 'Indonesia' },
  '364': { alpha2: 'IR', name: 'Iran' },
  '368': { alpha2: 'IQ', name: 'Iraq' },
  '372': { alpha2: 'IE', name: 'Ireland' },
  '376': { alpha2: 'IL', name: 'Israel' },
  '380': { alpha2: 'IT', name: 'Italy' },
  '384': { alpha2: 'CI', name: 'Côte d’Ivoire' },
  '388': { alpha2: 'JM', name: 'Jamaica' },
  '392': { alpha2: 'JP', name: 'Japan' },
  '398': { alpha2: 'KZ', name: 'Kazakhstan' },
  '400': { alpha2: 'JO', name: 'Jordan' },
  '404': { alpha2: 'KE', name: 'Kenya' },
  '408': { alpha2: 'KP', name: 'North Korea' },
  '410': { alpha2: 'KR', name: 'South Korea' },
  '414': { alpha2: 'KW', name: 'Kuwait' },
  '417': { alpha2: 'KG', name: 'Kyrgyzstan' },
  '418': { alpha2: 'LA', name: 'Laos' },
  '422': { alpha2: 'LB', name: 'Lebanon' },
  '426': { alpha2: 'LS', name: 'Lesotho' },
  '428': { alpha2: 'LV', name: 'Latvia' },
  '430': { alpha2: 'LR', name: 'Liberia' },
  '434': { alpha2: 'LY', name: 'Libya' },
  '440': { alpha2: 'LT', name: 'Lithuania' },
  '442': { alpha2: 'LU', name: 'Luxembourg' },
  '450': { alpha2: 'MG', name: 'Madagascar' },
  '454': { alpha2: 'MW', name: 'Malawi' },
  '458': { alpha2: 'MY', name: 'Malaysia' },
  '466': { alpha2: 'ML', name: 'Mali' },
  '478': { alpha2: 'MR', name: 'Mauritania' },
  '484': { alpha2: 'MX', name: 'Mexico' },
  '496': { alpha2: 'MN', name: 'Mongolia' },
  '498': { alpha2: 'MD', name: 'Moldova' },
  '499': { alpha2: 'ME', name: 'Montenegro' },
  '504': { alpha2: 'MA', name: 'Morocco' },
  '508': { alpha2: 'MZ', name: 'Mozambique' },
  '512': { alpha2: 'OM', name: 'Oman' },
  '516': { alpha2: 'NA', name: 'Namibia' },
  '524': { alpha2: 'NP', name: 'Nepal' },
  '528': { alpha2: 'NL', name: 'Netherlands' },
  '540': { alpha2: 'NC', name: 'New Caledonia' },
  '554': { alpha2: 'NZ', name: 'New Zealand' },
  '558': { alpha2: 'NI', name: 'Nicaragua' },
  '562': { alpha2: 'NE', name: 'Niger' },
  '566': { alpha2: 'NG', name: 'Nigeria' },
  '578': { alpha2: 'NO', name: 'Norway' },
  '586': { alpha2: 'PK', name: 'Pakistan' },
  '591': { alpha2: 'PA', name: 'Panama' },
  '598': { alpha2: 'PG', name: 'Papua New Guinea' },
  '600': { alpha2: 'PY', name: 'Paraguay' },
  '604': { alpha2: 'PE', name: 'Peru' },
  '608': { alpha2: 'PH', name: 'Philippines' },
  '616': { alpha2: 'PL', name: 'Poland' },
  '620': { alpha2: 'PT', name: 'Portugal' },
  '626': { alpha2: 'TL', name: 'Timor-Leste' },
  '630': { alpha2: 'PR', name: 'Puerto Rico' },
  '634': { alpha2: 'QA', name: 'Qatar' },
  '642': { alpha2: 'RO', name: 'Romania' },
  '643': { alpha2: 'RU', name: 'Russia' },
  '646': { alpha2: 'RW', name: 'Rwanda' },
  '682': { alpha2: 'SA', name: 'Saudi Arabia' },
  '686': { alpha2: 'SN', name: 'Senegal' },
  '688': { alpha2: 'RS', name: 'Serbia' },
  '694': { alpha2: 'SL', name: 'Sierra Leone' },
  '702': { alpha2: 'SG', name: 'Singapore' },
  '703': { alpha2: 'SK', name: 'Slovakia' },
  '704': { alpha2: 'VN', name: 'Vietnam' },
  '705': { alpha2: 'SI', name: 'Slovenia' },
  '706': { alpha2: 'SO', name: 'Somalia' },
  '710': { alpha2: 'ZA', name: 'South Africa' },
  '716': { alpha2: 'ZW', name: 'Zimbabwe' },
  '724': { alpha2: 'ES', name: 'Spain' },
  '728': { alpha2: 'SS', name: 'South Sudan' },
  '729': { alpha2: 'SD', name: 'Sudan' },
  '740': { alpha2: 'SR', name: 'Suriname' },
  '748': { alpha2: 'SZ', name: 'Eswatini' },
  '752': { alpha2: 'SE', name: 'Sweden' },
  '756': { alpha2: 'CH', name: 'Switzerland' },
  '760': { alpha2: 'SY', name: 'Syria' },
  '762': { alpha2: 'TJ', name: 'Tajikistan' },
  '764': { alpha2: 'TH', name: 'Thailand' },
  '768': { alpha2: 'TG', name: 'Togo' },
  '780': { alpha2: 'TT', name: 'Trinidad and Tobago' },
  '784': { alpha2: 'AE', name: 'United Arab Emirates' },
  '788': { alpha2: 'TN', name: 'Tunisia' },
  '792': { alpha2: 'TR', name: 'Türkiye' },
  '795': { alpha2: 'TM', name: 'Turkmenistan' },
  '800': { alpha2: 'UG', name: 'Uganda' },
  '804': { alpha2: 'UA', name: 'Ukraine' },
  '807': { alpha2: 'MK', name: 'North Macedonia' },
  '818': { alpha2: 'EG', name: 'Egypt' },
  '826': { alpha2: 'GB', name: 'United Kingdom' },
  '834': { alpha2: 'TZ', name: 'Tanzania' },
  '840': { alpha2: 'US', name: 'United States' },
  '854': { alpha2: 'BF', name: 'Burkina Faso' },
  '858': { alpha2: 'UY', name: 'Uruguay' },
  '860': { alpha2: 'UZ', name: 'Uzbekistan' },
  '862': { alpha2: 'VE', name: 'Venezuela' },
  '887': { alpha2: 'YE', name: 'Yemen' },
  '894': { alpha2: 'ZM', name: 'Zambia' },
};

export function lookupCountry(numericId: string | number): CountryInfo | null {
  const key = String(numericId).padStart(3, '0');
  return NUMERIC_TO_COUNTRY[key] ?? null;
}
